# Generated by Django 4.2.6 on 2023-11-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_category_options_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='experience',
            field=models.CharField(default='not provided', max_length=225),
        ),
        migrations.AddField(
            model_name='item',
            name='otherprojects',
            field=models.CharField(default='not provided', max_length=225),
        ),
    ]
