# Generated by Django 4.2.6 on 2024-01-31 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_item_experience_item_otherprojects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='item_images')),
                ('price', models.FloatField()),
                ('is_sold', models.BooleanField()),
                ('created_by', models.CharField(max_length=50)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('experience', models.CharField(default='not provided', max_length=225)),
                ('otherprojects', models.CharField(default='not provided', max_length=225)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='item.category')),
            ],
        ),
    ]
